version: "3.7"
services:
    parser_stage_openweather:
        image: avalancheforecast/main:pipe_parser_stage_openweather
        restart: always
        container_name: pipe_parser_stage_openweather
        env_file:
            - ../.env
